README.md
I apologize, I just realized I messed that up slightly. Corrected it
=> Correction on C#

README.md
Hi! 
Could you add this library: https://github.com/vitalets/websocket-as-promised
Thanks!
=> add websocket-as-promised

README.md
Hey! µWebSockets is also available for Node.js, so I have added it there.
=> Added uws for Node.js

README.md
https://eole-io.github.io/sandstone/
=> Added Sandstone for PHP

README.md
Hi there,
We just open-sourced our websocket library and I'd love it to be referenced on your curated list.
Thanks,
- Benjamin
=> Add a reference to IXWebSocket, a new C++ client library

README.md
Also fixes wrong URL to nhooyr/websocket
=> Centrifugo agnostic server and Centrifuge lib for Go

README.md
GUI testing client is important in WS testing because it's not easy to debug the code from the console for every message.
=> Add Firecamp in GUI testing list

README.md
I've added a new C implementation to your list.
This implementation might be useful to people who want to use websockets on unusual platforms. It should work over any transport layer but requires the user to do the integration work.
=> Added "WebSockets in C"

README.md
Added [Implementing a WebSocket server with Node.js](https://medium.com/hackernoon/implementing-a-websocket-server-with-node-js-d9b78ec5ffa8) tutorial to the list.
=> Add new tutorial in the list

README.md
I've added WebSocket King to the GUI list.
=> Add Websocket King

README.md
Add a couple of notable libraries to the list of awesome perl things. 
(Also search.cpan.org has been replaced by metacpan.org)
=> A couple more perl things

README.md
- soketi:  https://docs.soketi.app/ 
- laravel-websockets: https://beyondco.de/docs/laravel-websockets/getting-started/introduction
=> Add soketi and laravel-websockets

README.md
To make the links look cleaner..
=> Update perl links

README.md
this is actually the same thing once code and the other link is docs
=> merge python websockets

README.md
Add Ballerina WebSocketModule and Introduce Ballerina Language under `Tools per Language` section
=> Add Ballerina WebSocket Module

README.md
Added a new language `julia` and respective websocket libraries available for the language
=> Added julia lang and respective websocket libraries

README.md
Hey! I'd be really happy if you added my library.
Link to the docs: https://zilaws.com
=> Adding ZilaWS

README.md
[Foxglove Websocket Protocol](https://github.com/foxglove/ws-protocol) - A websocket protocol implementation for visualization
=> [Foxglove Websocket Protocol](https://github.com/foxglove/ws-protocol) - A websocket protocol implementation for visualization

README.md
I added GWS for golang, which is a great library and I thought I would add this to the libraries listed for Go.
=> feat: added GWS library for golang

README.md
Hello.
Thanks for the repository - many great links collected here.
With this PR I would like to introduce the description for [D language](https://dlang.org) solutions.
Most of the presented libraries are Web servers (that supports both HTTP and WebSockets).
WebsocketD is a specific WebSocket server.
=> Dlang libraries
